version: '3.8'

services:
  api:
    image: advenjourney/api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      API_SERVER_ADDR: ':8080'
      API_DB_DSN: 'postgresql://advenjourney:advenjourney@db/advenjourney?sslmode=disable'
    ports:
      - 8080:8080

  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: advenjourney
      POSTGRES_USER: advenjourney
      POSTGRES_DB: advenjourney
    ports:
      - 5432:5432
