name: CICD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35
          working-directory: api

      - name: assets-build
        run: make assets

      - name: make-api
        run: make build

      - name: container
        run: make container

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      # - name: Build and push latest
      #   id: docker_build
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: advenjourney/api:latest
      # - name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}

      - name: push to dockerhub
        run: make container-push

      - name: Staging deployment
        uses: appleboy/ssh-action@master
        with:
          host: 159.89.99.23 # staging.advenjourney.com
          USERNAME: ${{ secrets.STAGING_USERNAME }}
          PORT: ${{ secrets.STAGING_PORT }}
          KEY: ${{ secrets.STAGING_KEY }}
          script: |
            wget https://raw.githubusercontent.com/advenjourney/advenjourney/main/deploy/staging/docker-compose.yaml -O docker-compose.yaml
            docker-compose pull
            docker-compose up -d
