name: CICD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - uses: actions/setup-node@v2
        with:
          go-version: '^1.15.0'
          node-version: '15.x'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35
          working-directory: api

      - name: test-go
        run: go version

      - name: assets-build
        run: make assets

      - name: make-api
        run: make build

      - name: container
        run: make container

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to dockerhub
        run: make container-push
